### ISSUE TITLE
Unable to schedule posts

### ISSUE THREAD

**Issue by jasminetracey** [pauloamgomes/CockpitCMS-Moderation#11]
Good day, 
I am able to set up moderation with the various statuses however i am unable to set up a schedule event

**Comment by jasminetracey** [comment]
figured it out you have to config.php and not config.yaml

```php
<?php

return [
  'moderation' => [
    'schedule' => '*'
  ],
];
```

**Comment by pauloamgomes** [comment]
Glad you figured out the solution and apologies for not answering, but have been quite busy...
