### ISSUE TITLE
Specifying "lang" parameter value that is not in supported language configuration yields null values

### ISSUE THREAD

**Issue by gryphonmyers** [pauloamgomes/CockpitCMS-Moderation#13]
Repro steps:
1) Create a collection with a moderation field and at least one localized field. Publish a revision of an entry.
2) Save a new draft of the entry.
3) Query the entry on the rest API with a lang value of any unsupported language (e.g. lang=foobar). 
4) Note that localized fields are missing from the response.

Expected results:
To be consistent with the stock Cockpit behavior, default data should be returned when lang suffixed field is not found. This behavior should be bypassed with the ignoreDefaultFallback param, as seen here: https://github.com/agentejo/cockpit/blob/f28e568bdc448b0b4fa81e0676ce74e2f039b730/modules/Collections/bootstrap.php#L611

**Comment by pauloamgomes** [comment]
Thanks @gryphonmyers , I did a quick test and your fix/update seems to work, can you kindly confirm all good with that issue and close if so.

**Comment by gryphonmyers** [comment]
Yes thanks for the quick merge!
