### ISSUE TITLE
Clicking "publish and save" button, followed by "save draft" button (without refresh) causes changes to be saved in published state

### ISSUE THREAD

**Issue by gryphonmyers** [pauloamgomes/CockpitCMS-Moderation#15]
Repro steps:

1. Create new entry in collection with moderation field.
2. Publish the entry. 
3. RefreshNote that status switches to "Draft"
4. Make some edit, then click "publish & save" button. Note that status switches to published. 
5. Without refreshing, make more edits then click the "save draft" button.
6. Examine API responses to find that the "save draft" click resulted in data being saved to published state.

Expected results:
Clicking a button labeled "save draft" should never commit data to published state. Either this button should not be available in these circumstances, or the button's behavior should change to commit the change to draft state instead of published state.

**Comment by pauloamgomes** [comment]
Thanks @gryphonmyers for reporting and fixing!
