### ISSUE TITLE
Scheduled dates are unreliable depending on client / server time zones

### ISSUE THREAD

**Issue by gryphonmyers** [pauloamgomes/CockpitCMS-Moderation#17]
Currently, the client's date / time get written to the server as-is (in local time). The server will then do date calculations based on this client-specific local time, using the server-specific local time. This leads to unreliable / incorrect dates in every case other than the one where your server happens to be using the same time zone as every client / CMS user.

We can very easily make this reliable by converting dates to UTC before storing them to the server and converting them to local when rendering them from the server.

**Comment by pauloamgomes** [comment]
Thanks @gryphonmyers for reporting and fixing!
