### ISSUE TITLE
Not working with lates Cockpit CMS

### ISSUE THREAD

**Issue by 0x2A** [pauloamgomes/CockpitCMS-Moderation#2]
When installing the plugin on the latest cockpit version (master branch) I only get a 500 error. Log does not help very much since nothing is logged out... (/var/log/apache2/error.log)

**Comment by pauloamgomes** [comment]
Are you using Cockpit Next branch? This only works on Next

**Comment by 0x2A** [comment]
Yes, tried on latest commit of next branch.

**Comment by pauloamgomes** [comment]
I'm using it on many cockpit instances without issues, can you confirm you did exactly what is requied in the installation steps?

**Comment by 0x2A** [comment]
Ok my bad, it seems I missed the part with the folder name, had it still as CockpitCMS-Moderation-master. After renaming to Moderation it worked. 🤦‍♂️
