### ISSUE TITLE
Collections get autopopulated on when getting published state of a draft collection

### ISSUE THREAD

**Issue by habewe** [pauloamgomes/CockpitCMS-Moderation#20]
Steps:
Have a moderated collection with a field collectionlink.
Save as published
Save as draft
Call API without draft key to get old published state

ACTUAL
Collectionlink gets populated even without calling including "populate"-param

EXPECTED
Collectionlinks dont get populated without calling populate-param

FIX
We fixed it with changing actions.php line 86 to `$populated = cockpit_populate_collection($published, -1, $populate);`
cockpit_populate_collection expects maxlevel at second param and level at third. In the current state $populate has no meaning at all.
We dont know sideffects of the proposed fix and dont use populate ourselves, so no pull request.

**Comment by pauloamgomes** [comment]
@habewe you can pass on your request params `populate=0` 

in actions default for populate is 1:
```
$populate = $app->param('populate', 1);
```
