### ISSUE TITLE
No Access to Unpublished Items via API

### ISSUE THREAD

**Issue by markuslueckingmuc** [pauloamgomes/CockpitCMS-Moderation#24]
Unformtunataly there is currently not possibility to access Unpublished Items via API. Or is that somehow possible?

**Comment by pauloamgomes** [comment]
Hi @markuslueckingmuc , indeed, the main purpose was to only return:

- Published state - default behavior, you want to render only published entries in your website
- Draft state - behavior useful for implementing preview, you want to test something before publishing

Why do you need to access unpublished entries? What's your business case?

**Comment by pauloamgomes** [comment]
Closing due inactivity.
