### ISSUE TITLE
Automatically set to draft if changed?

### ISSUE THREAD

**Issue by JanSzidat** [pauloamgomes/CockpitCMS-Moderation#3]
Hi, thanks for this add-on. Is it possible to automatically set the status of a published collection entry to draft when the content has been changed?
Thanks
Jan

**Comment by pauloamgomes** [comment]
Well, by default is not, but it can be an interesting addition (something configurable in the field definition that defines default state on change).
In the meantime what you can do is implement a trigger `collections.save.before()` and change the value to draft.

**Comment by OB01** [comment]
Once something has been published, it shouldn't be unpublished by a change. Instead, the unchanged published revision should continue to be served until the new revision has been approved/moderated.

**Comment by pauloamgomes** [comment]
Hey @OB01 , not sure if understood properly, but an unpublished entry will never be returned! An entry on Draft state will return always the latest previously published version.

The addon was updated to change status to draft by default on the ui.
