### ISSUE TITLE
Support for "Localize"

### ISSUE THREAD

**Issue by fredrikkarlsson-pervanovo** [pauloamgomes/CockpitCMS-Moderation#5]
Hey @pauloamgomes and thanks for a great addon!

I am using localized fields in my collections and it would be awesome if this plugin could handle it.

Is this a sensible feature that you would like to chisel out or would you accept a PR?
I guess what needs to be done is to store the moderation status in localized field and check that field when fetching using "lang" parameter.

**Comment by pauloamgomes** [comment]
Hi @fredrikkarlsson-pervanovo , I'm happy about having a PR for that, any improvement and assuming that will not break with existing functionality it good. The issue may be on the events I'm triggering to restrict unpublished entries or retrieve the latest published when status is draft, but please dig on it.

Also, I'm implementing (should be done very soon) a scheduling feature, so maybe better wait for that.

**Comment by fredrikkarlsson-pervanovo** [comment]
So I assume you will do a rewrite that will make merging hard later?

**Comment by pauloamgomes** [comment]
No, its not a rewrite, the main structure doesn't change at all.

**Comment by fredrikkarlsson-pervanovo** [comment]
Ok, we will see who gets done first then :) Happy coding!

**Comment by fredrikkarlsson-pervanovo** [comment]
https://github.com/pauloamgomes/CockpitCMS-Moderation/pull/6

Here we go!

The only change of behaviour (except for it working with localized fields) is that the Unpublished status is not overwritten on mount with Draft as it was before. I guess it can be removed, but I feel that it makes the originalModeration better.

What do you think?

**Comment by pauloamgomes** [comment]
Thanks, merged and added some minor updates, namely:

1. If we don't have the localization active for the moderation field we can't check for lang field
2. When doing a request using filter/fields, we need to ensure that the non localized name is used (e.g. status instead of status_en)

Did several tests for both situations (localize and non localize) and it seems to be working well.

**Comment by fredrikkarlsson-pervanovo** [comment]
I have also tested it now and it seems to work good! Well done!

**Comment by pauloamgomes** [comment]
Thanks, in the meantime added the scheduling functionality.
