### ISSUE TITLE
Bug: Moderation Addon breaks the cockpit UI after update

### ISSUE THREAD

**Issue by diegozuber** [pauloamgomes/CockpitCMS-Moderation#7]
After I updated cockpit from 0.8.7 to 0.9.3 the moderation addon "stopped working".

Every field after the moderation field breaks:

See:
![Bildschirmfoto 2020-01-06 um 17 43 06 PM](https://user-images.githubusercontent.com/21689209/71832864-156a0800-30ac-11ea-913b-574b79c483a5.png)

After I put the moderation field at the end:
![Bildschirmfoto 2020-01-06 um 17 42 47 PM](https://user-images.githubusercontent.com/21689209/71832841-097e4600-30ac-11ea-8702-e2436b43d25b.png)

**Comment by pauloamgomes** [comment]
Hi @diegozuber , at first glance, the issue seems to be on Cockpit and not in the addon, can you confirm in your console inspector that you don't have any JS errors?

**Comment by diegozuber** [comment]
Hey @pauloamgomes. Thanks for your fast reply. Yes I had a JS error in the console. But it seems that this commit fixed it: https://github.com/pauloamgomes/CockpitCMS-Moderation/commit/7f2ec6b7306c9f380fe8dbb315bdb75638692420#diff-92cff01ccb69450c2e83d9cf4b6391b3
I installed the version 1.4 over a previous version of the moderation addon and I also had to delete the browser cache ;)
