### ISSUE TITLE
Doesn't show translated string 

### ISSUE THREAD

**Issue by YuriiLeso** [pauloamgomes/CockpitCMS-Moderation#8]
Hello, 
Thank you for the plugin! It's awesome!
I found one issue:
 _addons/Moderation/views/partials/entry-aside.php_ **line 65**
```
@lang("{entry[moderation_field])"})]
```
it doesn't translate `entry[moderation_field]` to user language as expected. The possible solution (works for me) is use `{App.i18n.get(entry[moderation_field])} ` instend of `@lang()`
Also, you forgot to put translation  at the line 61
The fix is same :)

BTW: Plugin is really good. Thank you for a gr8 work 

Cheers, 
Yurii

**Comment by pauloamgomes** [comment]
Thanks for addressing the issue. It's fixed now.
